package com.main.map_examen_sesiune.ORM.sql;

import com.main.map_examen_sesiune.ORM.annotations.columntype.FkRules;
import com.main.map_examen_sesiune.ORM.annotations.columntype.ForeignKey;
import com.main.map_examen_sesiune.ORM.annotations.columntype.NotNull;
import com.main.map_examen_sesiune.ORM.annotations.columntype.PrimaryKey;
import com.main.map_examen_sesiune.ORM.classparser.FieldsParser;
import com.main.map_examen_sesiune.ORM.exceptions.TypeConversionFailedException;

import java.lang.reflect.Field;

public class CreateTableWriter {
    public static String getScript(Class<?> cl) throws TypeConversionFailedException {
        StringBuilder res = new StringBuilder("CREATE TABLE " + cl.getSimpleName() + "(");
        for(Field field: FieldsParser.getAllFields(cl)){
            res.append(fieldResolve(field)).append(", ");
        }
        return res.toString().substring(0, res.length() - 2) + ")";
    }

    private static String primaryKey(Field field){
        PrimaryKey an = field.getAnnotation(PrimaryKey.class);
        if(an == null){
            return "";
        }
        return " PRIMARY KEY" + (an.autoInc()?" GENERATED BY DEFAULT AS IDENTITY": "");
    }

    private static String foreignKey(Field field){
        ForeignKey an = field.getAnnotation(ForeignKey.class);
        if(an == null){
            return "";
        }
        return ", FOREIGN KEY (" + field.getName() + ") REFERENCES " + an.entity().getSimpleName() +
                "(" + an.referencedColumn() + ")"
                + (an.rule() == FkRules.CASCADE?
                " ON DELETE CASCADE ON UPDATE CASCADE":
                an.rule() == FkRules.SET_NULL?
                        " ON DELETE SET NULL ON UPDATE SET NULL":"");
    }

    private static String fieldResolve(Field field) throws TypeConversionFailedException {
        return field.getName() + " " +  TypeConvertorJavaSQL.getSQLType(field.getType().getSimpleName())
                + primaryKey(field) +
                (field.getAnnotation(NotNull.class) != null? " NOT NULL": "")
                + foreignKey(field);
    }
}
